service:
- docker

env:
  global:
  - TERM=dumb
  - secure: rs34wHwsLTKMWTxLhfyWe7lbaYadcSAo0lyTxBdHinhH82ohWGVYpV7Zm3pbBH15BZv65pvqspgm2oNOExHBonZ1yhn3VUreso+4h+nf8mAwCjH+71MNTeuQo+d8Jky3SIeLvf4LqYZ6Zbf8yXksPF3DFG49M1S1KByIPmF+LT08pbZEptrsb+T6tuAIyWqMosx4Y4mKub9IgFjudtw42yd+sE4kihpVhW9ebw3wrZYtREXuZxIDfIvvjC+n5cEs0plm41725CVTv893WU6P3Kl0Gtkl6mER6HDLYPIKnSBrDFKvnmMSD7Sc3w/wPFaxfRayC4LB2til324+IcmFq8EeQ7mKRsEwQiIqWra8702/5v9+JH4JntO5lS8cs5osMEv7bf1+bI4+AFTb4S2PqjWFwuvts2yLOZ3tmpFMjHK666+Jaa63JBSVA4+Bhjn2+9hAeIVxhQuiT5oZ3fenHFC8cZV/ywDqjSWfzgoEWJNfiBAfl/ZQRgt1JBFSJrCVjaYIoqscj64L89KMzBu0wrkuepU3n4gJMGPX+7cv4CHcrzCXX3f3mpfiP58swfCh2bNNhuR1xCu7Yyus2UsFcrI5ell4b84Hl1nkY6pOZhr9cwiylSHkBM2TEZQlCRLqbATaFK8/4GpDcCjFey6tyrg6tqhflND+oiiR3WZQYo0=

language: java
jdk: oraclejdk8

install: true
before_script:
- sudo apt update -y >/dev/null 2>&1 || true
- sudo apt install -y --no-install-recommends curl jq libxml2-utils docker-ce python-pip >/dev/null 2>&1
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)

script:

- ./mvnw -U >/dev/null
- ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up
- wait_for 8080 5005 9990
- sleep 20
- |
  echo '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                          xmlns:dag="http://daggerok/">
           <soapenv:Header/>
           <soapenv:Body>
              <dag:greeting>
                 <arg0>Ololo</arg0>
              </dag:greeting>
           </soapenv:Body>
        </soapenv:Envelope>' | http post :8080/app/App 'content-type:application/xml'
- ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down

- bash ./gradlew >/dev/null 2>&1
- bash ./gradlew composeUp
- wait_for 8080 5005 9990
- sleep 5
- >
  echo '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                          xmlns:dag="http://daggerok/">
           <soapenv:Header/>
           <soapenv:Body>
              <dag:greeting>
                 <arg0>Ololo</arg0>
              </dag:greeting>
           </soapenv:Body>
        </soapenv:Envelope>' | http post :8080/app/App 'content-type:application/xml'
- bash ./gradlew composeDown

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
