service:
- docker

env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

install: true
before_script:
- sudo apt update -y >/dev/null 2>&1 || true
- sudo apt install -y --no-install-recommends curl jq libxml2-utils docker-ce python-pip >/dev/null 2>&1
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)

script:

- ./mvnw -U >/dev/null
- ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up
- wait_for 8080 5005 9990
- sleep 20
- |
  echo '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                          xmlns:dag="http://daggerok/">
           <soapenv:Header/>
           <soapenv:Body>
              <dag:greeting>
                 <arg0>Ololo</arg0>
              </dag:greeting>
           </soapenv:Body>
        </soapenv:Envelope>' | http post :8080/app/App 'content-type:application/xml'
- curl -XPOST http://0.0.0.0:8080/app/App --header "content-type:text/xml" -d @request.xml | xmllint --format -
- ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down

- bash ./gradlew >/dev/null 2>&1
- bash ./gradlew composeUp
- wait_for 8080 5005 9990
- sleep 5
- curl -XPOST http://0.0.0.0:8080/app/App --header "content-type:text/xml" -d @request.xml | xmllint --format -
- >
  echo '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                          xmlns:dag="http://daggerok/">
           <soapenv:Header/>
           <soapenv:Body>
              <dag:greeting>
                 <arg0>Ololo</arg0>
              </dag:greeting>
           </soapenv:Body>
        </soapenv:Envelope>' | http post :8080/app/App 'content-type:application/xml'
- bash ./gradlew composeDown

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
